apiVersion: v2
name: ceilometer
description: A Helm chart for Openstack Ceilometer
type: application
version: 4.0.0
appVersion: "24.0.1-9-g5bd0ae446-2-10"
sources:
  - https://github.com/NeCTAR-RC/ceilometer-helm.git
dependencies:
  - name: nectarlib
    version: 3.2.0
    repository: oci://registry.rc.nectar.org.au/nectar-helm
